### ISSUE TITLE
Toggle size

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#141]
The toggle size for sharing/email updates is smaller than the default size for the platform.  Use default size (or whatever the UI guidelines recommend).  

It's possible that these are scalable as an accessibility feature. Test this.

**Comment by mohinderps** [comment]
It is because of the following style applied to switch(toggle):

`transform: [{ scale: 0.8 }]`

Should that be removed? Even if it is removed, there would be only slight increase in the size, nowhere close to the one in MVP. 

Plus they both the switches(MVP and app) look different. That also need to be done.
