### ISSUE TITLE
Content too wide

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#163]
If multiple trash items are selected, it pushes the heart too far, and it's cut off on the right (Android only)

<img width="699" alt="Screen Shot 2020-03-17 at 8 38 35 PM" src="https://user-images.githubusercontent.com/8822863/76914170-c3a1e300-688f-11ea-9c8e-be0ba8c28064.png">

**Comment by k-charette** [comment]
This issue was also showing up on iPhone too. 
After adding a flex: 1 to the subText styling it seemed to fix the issue. Tested on iPhone 11 Pro Max and on my Galaxy S9 and looks to be fixed. 

Screenshot taken from my phone. 
![20200324_122324](https://user-images.githubusercontent.com/19808794/77451066-8cb95900-6dca-11ea-8500-d067d2c656f6.jpg)
