### ISSUE TITLE
Update icon colors

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#167]
Change the color of the following icons to gray #666666:

Plog page: camera and people icons;
History: achievement icons;
Local: filled in heart;

**Comment by ValerieKenyon** [comment]
I'll see what I can do for this one.

**Comment by ValerieKenyon** [comment]
Camera icons on PlogScreen: 
![Screen Shot 2020-03-31 at 16 14 19](https://user-images.githubusercontent.com/35377991/78071066-d1189c00-736a-11ea-9a7f-87459a39afd1.png)

Heart on local screen, at lower right of screenshot: 
![Screen Shot 2020-03-31 at 16 14 03](https://user-images.githubusercontent.com/35377991/78071123-ec83a700-736a-11ea-8981-772b5da3523e.png)

Because Achievements are disabled, I don't have a screenshot, but I did change the color from `#ac8dd8` to `#666666` in all the icons in the appropriate folder (achievement_badges_48_48).

**Comment by ValerieKenyon** [comment]
Still working on the people icons

**Comment by kaniasty** [comment]
The filled in heart (one or more likes) still looks too light.  Needs to be darkened.

**Comment by ValerieKenyon** [comment]
I'll try some different darknesses later on today (Wed 2020_4_22).
