### ISSUE TITLE
Weather not shown

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#96]
(I think this may not be a real issue - I need to test)

@ValerieKenyon I think you explained to me why this happens - can you add a comment here since I don't remember the detail?

Instead of the weather, I see "Sorry, we can't give you weather info right now!"

This might be related to the 'Missing API' alert I get on this screen sometimes.

- Fix the issue (or tell me where/how to get a custom API key for Plogalong)
- If weather can't be shown,  just say "Every plogging day is a good day."

**Comment by kaniasty** [comment]
I no longer see an API alert, but on IOS simulator I don't see custom message, just "Every plogging day..."

**Comment by ValerieKenyon** [comment]
The message you're seeing is the default message.  There's a reason for this.  We don't want to have our API key publicly visible on GitHub while we're in development.  We've tested the code with the API key and it works - we're just deleting the API key in our code that gets posted to GitHub, so that the key can't be stolen.

**Comment by kaniasty** [comment]
Check readme for instructions on openweather API
